name = "family-album"
pages_build_output_dir = "public"

# Binding D1 Database (Database ID diisi setelah langkah pembuatan D1 di Cloudflare)
[[d1_databases]]
binding = "DB"
database_name = "family-album-db"
database_id = "bcf9f33f-cbeb-49c3-8f2b-94e7d8055d84"
